// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/mistandok/platform_common/pkg/db"
	mock "github.com/stretchr/testify/mock"

	pgconn "github.com/jackc/pgx/v5/pgconn"

	pgx "github.com/jackc/pgx/v5"
)

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

type DB_Expecter struct {
	mock *mock.Mock
}

func (_m *DB) EXPECT() *DB_Expecter {
	return &DB_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, txOptions
func (_m *DB) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _m.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return rf(ctx, txOptions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = rf(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = rf(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DB_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type DB_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *DB_Expecter) BeginTx(ctx interface{}, txOptions interface{}) *DB_BeginTx_Call {
	return &DB_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *DB_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *DB_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.TxOptions))
	})
	return _c
}

func (_c *DB_BeginTx_Call) Return(_a0 pgx.Tx, _a1 error) *DB_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DB_BeginTx_Call) RunAndReturn(run func(context.Context, pgx.TxOptions) (pgx.Tx, error)) *DB_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *DB) Close() {
	_m.Called()
}

// DB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DB_Expecter) Close() *DB_Close_Call {
	return &DB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DB_Close_Call) Run(run func()) *DB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DB_Close_Call) Return() *DB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *DB_Close_Call) RunAndReturn(run func()) *DB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFromContext provides a mock function with given fields: ctx, tableName, columnNames, rowSrc
func (_m *DB) CopyFromContext(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	ret := _m.Called(ctx, tableName, columnNames, rowSrc)

	if len(ret) == 0 {
		panic("no return value specified for CopyFromContext")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) (int64, error)); ok {
		return rf(ctx, tableName, columnNames, rowSrc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) int64); ok {
		r0 = rf(ctx, tableName, columnNames, rowSrc)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) error); ok {
		r1 = rf(ctx, tableName, columnNames, rowSrc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DB_CopyFromContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFromContext'
type DB_CopyFromContext_Call struct {
	*mock.Call
}

// CopyFromContext is a helper method to define mock.On call
//   - ctx context.Context
//   - tableName pgx.Identifier
//   - columnNames []string
//   - rowSrc pgx.CopyFromSource
func (_e *DB_Expecter) CopyFromContext(ctx interface{}, tableName interface{}, columnNames interface{}, rowSrc interface{}) *DB_CopyFromContext_Call {
	return &DB_CopyFromContext_Call{Call: _e.mock.On("CopyFromContext", ctx, tableName, columnNames, rowSrc)}
}

func (_c *DB_CopyFromContext_Call) Run(run func(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource)) *DB_CopyFromContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Identifier), args[2].([]string), args[3].(pgx.CopyFromSource))
	})
	return _c
}

func (_c *DB_CopyFromContext_Call) Return(_a0 int64, _a1 error) *DB_CopyFromContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DB_CopyFromContext_Call) RunAndReturn(run func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) (int64, error)) *DB_CopyFromContext_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, q, args
func (_m *DB) ExecContext(ctx context.Context, q db.Query, args ...interface{}) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, q)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.Query, ...interface{}) (pgconn.CommandTag, error)); ok {
		return rf(ctx, q, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.Query, ...interface{}) pgconn.CommandTag); ok {
		r0 = rf(ctx, q, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.Query, ...interface{}) error); ok {
		r1 = rf(ctx, q, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DB_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type DB_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - q db.Query
//   - args ...interface{}
func (_e *DB_Expecter) ExecContext(ctx interface{}, q interface{}, args ...interface{}) *DB_ExecContext_Call {
	return &DB_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, q}, args...)...)}
}

func (_c *DB_ExecContext_Call) Run(run func(ctx context.Context, q db.Query, args ...interface{})) *DB_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(db.Query), variadicArgs...)
	})
	return _c
}

func (_c *DB_ExecContext_Call) Return(_a0 pgconn.CommandTag, _a1 error) *DB_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DB_ExecContext_Call) RunAndReturn(run func(context.Context, db.Query, ...interface{}) (pgconn.CommandTag, error)) *DB_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *DB) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DB_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type DB_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DB_Expecter) Ping(ctx interface{}) *DB_Ping_Call {
	return &DB_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *DB_Ping_Call) Run(run func(ctx context.Context)) *DB_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DB_Ping_Call) Return(_a0 error) *DB_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DB_Ping_Call) RunAndReturn(run func(context.Context) error) *DB_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, q, args
func (_m *DB) QueryContext(ctx context.Context, q db.Query, args ...interface{}) (pgx.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, q)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 pgx.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.Query, ...interface{}) (pgx.Rows, error)); ok {
		return rf(ctx, q, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.Query, ...interface{}) pgx.Rows); ok {
		r0 = rf(ctx, q, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.Query, ...interface{}) error); ok {
		r1 = rf(ctx, q, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DB_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type DB_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - q db.Query
//   - args ...interface{}
func (_e *DB_Expecter) QueryContext(ctx interface{}, q interface{}, args ...interface{}) *DB_QueryContext_Call {
	return &DB_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, q}, args...)...)}
}

func (_c *DB_QueryContext_Call) Run(run func(ctx context.Context, q db.Query, args ...interface{})) *DB_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(db.Query), variadicArgs...)
	})
	return _c
}

func (_c *DB_QueryContext_Call) Return(_a0 pgx.Rows, _a1 error) *DB_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DB_QueryContext_Call) RunAndReturn(run func(context.Context, db.Query, ...interface{}) (pgx.Rows, error)) *DB_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, q, args
func (_m *DB) QueryRowContext(ctx context.Context, q db.Query, args ...interface{}) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, q)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, db.Query, ...interface{}) pgx.Row); ok {
		r0 = rf(ctx, q, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// DB_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type DB_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - q db.Query
//   - args ...interface{}
func (_e *DB_Expecter) QueryRowContext(ctx interface{}, q interface{}, args ...interface{}) *DB_QueryRowContext_Call {
	return &DB_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, q}, args...)...)}
}

func (_c *DB_QueryRowContext_Call) Run(run func(ctx context.Context, q db.Query, args ...interface{})) *DB_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(db.Query), variadicArgs...)
	})
	return _c
}

func (_c *DB_QueryRowContext_Call) Return(_a0 pgx.Row) *DB_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DB_QueryRowContext_Call) RunAndReturn(run func(context.Context, db.Query, ...interface{}) pgx.Row) *DB_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewDB creates a new instance of DB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *DB {
	mock := &DB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
